//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente_endereco
    {
        public int id { get; set; }
        public int id_cliente { get; set; }
        public int id_estado { get; set; }
        public int id_cidade { get; set; }
        public string nome { get; set; }
        public string cep { get; set; }
        public string endereco { get; set; }
        public string numero { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
    
        public virtual cidade cidade { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual estado estado { get; set; }
    }
}
