//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ecombaseEntities : DbContext
    {
        public ecombaseEntities()
            : base("name=ecombaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<banner> banner { get; set; }
        public virtual DbSet<banner_arquivos> banner_arquivos { get; set; }
        public virtual DbSet<carrinho> carrinho { get; set; }
        public virtual DbSet<carrinho_produto> carrinho_produto { get; set; }
        public virtual DbSet<cidade> cidade { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<cliente_endereco> cliente_endereco { get; set; }
        public virtual DbSet<estado> estado { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<pedido> pedido { get; set; }
        public virtual DbSet<pedido_produto> pedido_produto { get; set; }
        public virtual DbSet<produto> produto { get; set; }
        public virtual DbSet<produto_imagem> produto_imagem { get; set; }
        public virtual DbSet<sexo> sexo { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<log> log { get; set; }
        public virtual DbSet<log_tipo> log_tipo { get; set; }
    }
}
