//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto_imagem
    {
        public int id { get; set; }
        public int id_produto { get; set; }
        public string nome { get; set; }
        public bool ativo { get; set; }
        public bool padrao { get; set; }
    
        public virtual produto produto { get; set; }
    }
}
